import{i as f,a as b,S as L}from"./assets/vendor-89feecc5.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();let d=1,M=!1,p;const g=40,$=document.querySelector("form"),k=document.getElementById("searchInput"),y=document.getElementById("gallery"),i=document.getElementById("loader"),r=document.getElementById("loadMore");$.addEventListener("submit",async function(c){c.preventDefault(),d=1,y.innerHTML="",i.classList.remove("hide"),r.style.display="none";const s="41459044-8203682bce4ef2c3a7a872845";if(p=k.value.trim(),p===""){i.classList.add("hide"),f.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}const t=`https://pixabay.com/api/?key=${s}&q=${p}&image_type=photo&orientation=horizontal&safesearch=${!0}&page=${d}&per_page=${g}`;try{const a=(await b.get(t)).data.hits;if(a.length>0){const u=v(a);i.classList.add("hide"),y.insertAdjacentHTML("beforeend",u);const h=new L(".image-card a");a.length===g?r.style.display="block":(r.style.display="none",f.info({message:"We are sorry, but you reached the end of search results.",position:"topRight"})),r.addEventListener("click",async function(m){d++,await w()})}else r.style.display="none"}catch(o){console.error("Помилка при виконанні запиту:",o)}finally{$.reset()}});function v(c){return c.map(({webformatURL:s,tags:l,likes:n,views:e,comments:t,downloads:o})=>`
    <div class="image-card">
      <a href="${s}" class="lightbox-trigger">
        <img src="${s}" alt="${l}">
      </a>
      <div class="image-details">
        <p><strong>Likes:</strong> ${n}</p>
        <p><strong>Views:</strong> ${e}</p>
        <p><strong>Comments:</strong> ${t}</p>
        <p><strong>Downloads:</strong> ${o}</p>
      </div>
    </div>
  `).join("")}async function w(){const e=`https://pixabay.com/api/?key=41459044-8203682bce4ef2c3a7a872845&q=${p}&image_type=photo&orientation=horizontal&safesearch=${!0}&page=${d}&per_page=${g}`;try{i.classList.remove("hide"),r.style.display="none";const t=await b.get(e),o=t.data.hits;if(o.length>0){const a=v(o);y.insertAdjacentHTML("beforeend",a),y.insertAdjacentHTML("beforeend",a);const{height:u}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:u*2,behavior:"smooth"});const h=new L(".image-card a"),m=Math.ceil(t.data.totalHits/g);d>=m?(r.style.display="none",M=!0,i.classList.add("hide"),f.info({message:"We are sorry, but you reached the end of search results.",position:"topRight"})):r.style.display="block",h.refresh()}else r.style.display="none"}catch(t){console.error("Помилка при виконанні запиту:",t)}finally{i.classList.add("hide")}}
//# sourceMappingURL=commonHelpers.js.map
