import{i as h,a as $,S as b}from"./assets/vendor-89feecc5.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();let l=1,v=!1,d;const p=40,m=document.querySelector("form"),M=document.getElementById("searchInput"),y=document.getElementById("gallery"),u=document.getElementById("loader"),r=document.getElementById("loadMore");m.addEventListener("submit",async function(n){n.preventDefault(),l=1,y.innerHTML="",u.classList.remove("hide"),r.style.display="none";const s="41459044-8203682bce4ef2c3a7a872845";if(d=M.value.trim(),d===""){u.classList.add("hide"),h.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}const t=`https://pixabay.com/api/?key=${s}&q=${d}&image_type=photo&orientation=horizontal&safesearch=${!0}&page=${l}&per_page=${p}`;try{const c=(await $.get(t)).data.hits;if(c.length>0){const g=L(c);u.classList.add("hide"),y.insertAdjacentHTML("beforeend",g);const f=new b(".image-card a");c.length===p?r.style.display="block":r.style.display="none",r.addEventListener("click",async function(E){l++,await k()})}else r.style.display="none"}catch(o){console.error("Помилка при виконанні запиту:",o)}finally{m.reset()}});function L(n){return n.map(({webformatURL:s,tags:i,likes:a,views:e,comments:t,downloads:o})=>`
    <div class="image-card">
      <a href="${s}" class="lightbox-trigger">
        <img src="${s}" alt="${i}">
      </a>
      <div class="image-details">
        <p><strong>Likes:</strong> ${a}</p>
        <p><strong>Views:</strong> ${e}</p>
        <p><strong>Comments:</strong> ${t}</p>
        <p><strong>Downloads:</strong> ${o}</p>
      </div>
    </div>
  `).join("")}async function k(){const e=`https://pixabay.com/api/?key=41459044-8203682bce4ef2c3a7a872845&q=${d}&image_type=photo&orientation=horizontal&safesearch=${!0}&page=${l}&per_page=${p}`;try{const t=await $.get(e),o=t.data.hits;if(o.length>0){const c=L(o);y.innerHTML+=c;const g=new b(".image-card a"),f=Math.ceil(t.data.totalHits/p);l>=f?(r.style.display="none",v=!0,h.info({message:"We are sorry, but you reached the end of search results.",position:"topRight"})):r.style.display="block",g.refresh()}else r.style.display="none"}catch(t){console.error("Помилка при виконанні запиту:",t)}finally{}}
//# sourceMappingURL=commonHelpers.js.map
